# Generated by Django 6.1.1 on 2026-09-10 19:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contact_messages',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='WalletAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('solde', models.DecimalField(decimal_places=2, default=800, max_digits=12)),
                ('total_genere', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'wallet_admin',
            },
        ),
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('numero_suivi', models.CharField(max_length=30, unique=True)),
                ('nom_colis', models.CharField(max_length=200)),
                ('type_produit', models.CharField(max_length=30)),
                ('nombre_produits', models.PositiveIntegerField(default=1)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dimensions', models.CharField(blank=True, default='', max_length=50)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('adresse_depart', models.CharField(max_length=255)),
                ('adresse_destination', models.CharField(max_length=255)),
                ('date_limite', models.DateField()),
                ('image_colis', models.CharField(blank=True, default='', max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('prix_estime', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'colis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('note', models.PositiveSmallIntegerField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('statut', models.CharField(default='approuve', max_length=20)),
                ('transporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avis_recus', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('colis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avis', to='shipping.colis')),
            ],
            options={
                'db_table': 'avis',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('lu', models.BooleanField(default=False)),
                ('colis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifs_admin', to='shipping.colis')),
            ],
            options={
                'db_table': 'notifications_admin',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echoue', 'Échoué'), ('rembourse', 'Remboursé')], default='en_attente', max_length=20)),
                ('numero_transaction', models.CharField(blank=True, default='', max_length=100)),
                ('operateur', models.CharField(blank=True, default='', max_length=50)),
                ('methode', models.CharField(blank=True, default='mobile_money', max_length=30)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='shipping.colis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paiements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('transporteur', 'Transporteur'), ('admin', 'Admin')], default='transporteur', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frais', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('paye', 'Payé'), ('rejete', 'Rejeté')], default='demande', max_length=20)),
                ('methode', models.CharField(default='mobile_money', max_length=30)),
                ('numero', models.CharField(max_length=30)),
                ('operateur', models.CharField(blank=True, default='', max_length=50)),
                ('reference_kkiapay', models.CharField(blank=True, default='', max_length=100)),
                ('reference_transaction', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retraits',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='SuiviColis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Livré', 'Livré')], default='En attente', max_length=20)),
                ('commentaire', models.TextField(blank=True, default='')),
                ('auteur_id', models.IntegerField(blank=True, null=True)),
                ('date_etape', models.DateTimeField(default=django.utils.timezone.now)),
                ('demande_livraison', models.BooleanField(default=False)),
                ('confirme_par_admin', models.BooleanField(default=False)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to='shipping.colis')),
            ],
            options={
                'db_table': 'suivi_colis',
                'ordering': ['date_etape'],
            },
        ),
        migrations.CreateModel(
            name='Transporteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('numero_permis', models.CharField(blank=True, default='', max_length=50)),
                ('vehicule', models.CharField(blank=True, default='', max_length=100)),
                ('compagnie', models.CharField(blank=True, default='', max_length=100)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('ville', models.CharField(blank=True, default='', max_length=100)),
                ('pays', models.CharField(blank=True, default='', max_length=100)),
                ('photo_vehicule', models.CharField(blank=True, default='', max_length=500)),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_en_attente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporteur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transporteurs',
            },
        ),
        migrations.CreateModel(
            name='Voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('numero_permis', models.CharField(max_length=50)),
                ('vehicule', models.CharField(max_length=100)),
                ('compagnie', models.CharField(blank=True, default='', max_length=100)),
                ('adresse', models.CharField(blank=True, default='', max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('pays_depart', models.CharField(max_length=100)),
                ('pays_destination', models.CharField(max_length=100)),
                ('date_depart', models.DateField()),
                ('heure_depart', models.TimeField()),
                ('poids_max', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telephone', models.CharField(blank=True, default='', max_length=30)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé')], default='en_attente', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voyages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voyages',
                'ordering': ['-date_depart', '-heure_depart'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('accepte', 'Accepté'), ('refuse', 'Refusé'), ('termine', 'Terminé')], default='en_attente', max_length=20)),
                ('colis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shipping.colis')),
                ('transporteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('voyage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='shipping.voyage')),
            ],
            options={
                'db_table': 'reservations',
                'unique_together': {('colis', 'voyage')},
            },
        ),
    ]
