# Generated by Django 5.2.17 on 2026-09-19 20:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0003_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('sujet', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('montant_reclame', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('rejete', 'Rejeté')], default='ouvert', max_length=20)),
                ('resolution', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'litiges',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RenameIndex(
            model_name='colis',
            new_name='colis_statut_bfc51a_idx',
            old_name='colis_statut_created_idx',
        ),
        migrations.RenameIndex(
            model_name='colis',
            new_name='colis_user_id_f53632_idx',
            old_name='colis_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='colis',
            new_name='colis_ville_74eb4b_idx',
            old_name='colis_ville_pays_idx',
        ),
        migrations.RenameIndex(
            model_name='colis',
            new_name='colis_date_li_539b41_idx',
            old_name='colis_date_limite_idx',
        ),
        migrations.RenameIndex(
            model_name='paiement',
            new_name='paiements_user_id_15f553_idx',
            old_name='paiement_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paiement',
            new_name='paiements_colis_i_93936e_idx',
            old_name='paiement_colis_idx',
        ),
        migrations.RenameIndex(
            model_name='paiement',
            new_name='paiements_statut_ce5cce_idx',
            old_name='paiement_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='paiement',
            new_name='paiements_numero__4b3722_idx',
            old_name='paiement_tx_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_statut_d20d98_idx',
            old_name='reservation_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_colis_i_3f47f1_idx',
            old_name='reservation_colis_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_voyage__ff8fe2_idx',
            old_name='reservation_voyage_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_transpo_cd3ebc_idx',
            old_name='reservation_transporteur_idx',
        ),
        migrations.RenameIndex(
            model_name='suivicolis',
            new_name='suivi_colis_colis_i_f17743_idx',
            old_name='suivi_colis_date_idx',
        ),
        migrations.RenameIndex(
            model_name='suivicolis',
            new_name='suivi_colis_statut_0e09ae_idx',
            old_name='suivi_statut_idx',
        ),
        migrations.RenameIndex(
            model_name='suivicolis',
            new_name='suivi_colis_demande_fe160d_idx',
            old_name='suivi_demande_liv_idx',
        ),
        migrations.RenameIndex(
            model_name='voyage',
            new_name='voyages_statut_c82d61_idx',
            old_name='voyage_statut_depart_idx',
        ),
        migrations.RenameIndex(
            model_name='voyage',
            new_name='voyages_ville_e613b1_idx',
            old_name='voyage_ville_idx',
        ),
        migrations.RenameIndex(
            model_name='voyage',
            new_name='voyages_pays_de_f56d0b_idx',
            old_name='voyage_pays_idx',
        ),
        migrations.AddField(
            model_name='paiement',
            name='rembourse',
            field=models.BooleanField(default=False, help_text='Remboursement effectué'),
        ),
        migrations.AddField(
            model_name='suivicolis',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='suivicolis',
            name='signature_data',
            field=models.TextField(blank=True, default='', help_text='Signature canvas base64'),
        ),
        migrations.AddField(
            model_name='suivicolis',
            name='signature_nom',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='walletadmin',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='litige',
            name='colis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges', to='shipping.colis'),
        ),
        migrations.AddField(
            model_name='litige',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to=settings.AUTH_USER_MODEL),
        ),
    ]
